#!/bin/sh
# Realistic content for listing screenshots: replaces perf/seed posts with a
# handful of article-like posts whose links cover every verdict.
cd "$(dirname "$0")" || exit 1
wp() { docker compose run --rm -T cli "$@"; }
# One wp-cli call, not one container per post.
docker compose run --rm -T cli eval 'foreach (get_posts(array("post_type" => "post", "post_status" => "any", "posts_per_page" => -1, "fields" => "ids")) as $id) wp_delete_post($id, true); foreach (get_comments(array("fields" => "ids")) as $c) wp_delete_comment($c, true); echo "cleared\n";' 2>&1 | grep -v "^ Container"
mk() { wp post create --post_status=publish --post_title="$1" --post_content="$2" --post_date="$3" >/dev/null; }
mk "How we cut our build times in half" '<!-- wp:paragraph --><p>Most of the win came from caching, following the approach in <a href="https://github.com/hxckya/this-repo-does-not-exist-404">this reference implementation</a> and the notes on <a href="https://developer.mozilla.org/en-US/docs/Web/API/Cache">the Cache API</a>. Our earlier write-up is <a href="/about/">here</a>.</p><!-- /wp:paragraph -->' "2025-11-03 09:12:00"
mk "Reading list: distributed systems" '<!-- wp:paragraph --><p>Start with the classic <a href="https://www.microsoft.com/en-us/research/publication/the-byzantine-generals-problem/">Byzantine Generals paper</a>, then <a href="http://github.com/hxckya">our examples repo</a>. The old mirror at <a href="https://10.255.255.1/papers/">the lab server</a> has been unreliable.</p><!-- /wp:paragraph -->' "2026-01-19 14:40:00"
mk "Interview: shipping a plugin to 100k sites" '<!-- wp:paragraph --><p>Our guest is on <a href="https://www.linkedin.com/in/someone-real">LinkedIn</a> and wrote about the launch in <a href="/no-such-page-xyz/">an earlier post</a>. Slides: <a href="https://example.com/decks/2024/plugin-launch.pdf">PDF</a>.</p><!-- /wp:paragraph --><!-- wp:image --><figure class="wp-block-image"><img src="https://example.com/images/interview-cover.jpg" alt="Cover"/></figure><!-- /wp:image -->' "2026-03-08 11:00:00"
mk "Notes from the accessibility audit" '<!-- wp:paragraph --><p>We followed <a href="https://www.w3.org/WAI/WCAG21/quickref/">the WCAG quick reference</a> and the checklist in <a href="https://github.com/hxckya/this-repo-does-not-exist-404">the shared repo</a>. Contrast tooling: <a href="https://webaim.org/resources/contrastchecker/">WebAIM</a>.</p><!-- /wp:paragraph -->' "2026-05-22 16:25:00"
mk "Migrating comments off a third-party service" '<!-- wp:paragraph --><p>The export format is documented <a href="https://example.com/docs/export-format-v1">here</a>; the import script lives in <a href="https://github.com/hxckya/pkgtruth">pkgtruth</a> (wrong repo, will fix) and the spec on <a href="https://www.rfc-editor.org/rfc/rfc8259">RFC 8259</a>.</p><!-- /wp:paragraph -->' "2026-07-14 10:05:00"
mk "What changed in our hosting setup" '<!-- wp:paragraph --><p>Status page: <a href="https://www.githubstatus.com/">GitHub Status</a>. Runbook: <a href="/wp-content/uploads/2026/07/runbook.pdf">internal PDF</a>. Vendor portal: <a href="https://www.linkedin.com/company/some-vendor">LinkedIn</a>.</p><!-- /wp:paragraph -->' "2026-08-30 08:45:00"
docker compose run --rm -T cli eval 'LinkSentinel_Scanner::start(true); for ($i=0;$i<30 && LinkSentinel_Scanner::is_running();$i++) LinkSentinel_Scanner::step(10); $s=LinkSentinel_Scanner::state(); $c=LinkSentinel_DB::counts(); printf("phase=%s found=%d broken=%d redirect=%d blocked=%d error=%d ok=%d\n",$s["phase"],$s["found"],$c["broken"],$c["redirect"],$c["blocked"],$c["error"],$c["ok"]);' 2>&1 | grep -v "^ Container"
